version: '3.8'

services:
  gbms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gbms_production
    ports:
      - "3005:3005"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: always
